### ISSUE TITLE
Bug Report: Compiling issues

### ISSUE THREAD

**Issue by DeadSyntaxdev** [EyeDaleHim/Crow-Engine#10]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows 11 64 bit

## What version of the game are you using? Look in the bottom left corner of the main menu.

Can't tell because I can't compile but I downloaded it like a second ago.

## Please describe your issue. Provide extensive detail and images if possible.
Problems with compiling mainly 2: Some things are now not working due to the removal of flx sprite and flixel.util.FLAxes has no field of x or y?

![image](https://user-images.githubusercontent.com/81271362/206831893-e9d3679d-954f-4b4c-a087-791cba340226.png)

**Comment by EyeDaleHim** [comment]
Please check your Flixel version, Crow Engine is not going to be on Flixel 4.11.0, you should be on 5.0.0.

Command Prompt:
```
haxelib update flixel
[Y]
haxelib update flixel-addons
[Y]
```

**Comment by DeadSyntaxdev** [comment]
Aight it worked.
