### ISSUE TITLE
Enhancement: Make a Proper Github Actions YAML

### ISSUE THREAD

**Issue by Raltyro** [EyeDaleHim/Crow-Engine#12]
Self-Explanatory

I'll probably make a pull request doing this

**Comment by SwickTheGreat** [comment]
was considering doing this, actions might come a bit later. but yeah we'll add them in.

**Comment by Raltyro** [comment]
Oh so i don't need to make a pull request for this then... :(

**Comment by Raltyro** [comment]
Oh! nevermind, https://github.com/EyeDaleHim/Crow-Engine/pull/16
