### ISSUE TITLE
Pressing keys with ghost tap on makes no miss noise, nor does it affect accuracy.

### ISSUE THREAD

**Issue by typhyte** [EyeDaleHim/Crow-Engine#13]
When you have the ghost tapping option off, pressing a key will give you a miss, but will not make bf play a miss animation or make a miss sound. The misses will also not count towards your overall accuracy.

Ex.

https://user-images.githubusercontent.com/43316541/224593870-c3f8ec39-dcdc-4d52-90ab-8267ec8664c5.mp4

**Comment by EyeDaleHim** [comment]
All are bugs to me, except the accuracy part, missing a note only counts for that.

**Comment by typhyte** [comment]
> All are bugs to me, except the accuracy part

imo if ghost tap misses dont count toward accuracy, make the taps remove health and dont let them add misses.
