### ISSUE TITLE
Enhancement: Add the currently-absent background music to the first two week 7 cutscenes

### ISSUE THREAD

**Issue by sweetcarolinaa** [EyeDaleHim/Crow-Engine#15]
In the original week 7 cutscenes, the song _Klaskii Romper_ is used in the background. Although it's usually muffled to not draw away from the dialogue, I noticed pretty quickly that it seems to be missing from Ugh and Guns, making the cutscenes feel a tiny bit empty. I'm not sure if this is intentional or not, but I think it would improve them immensely.

**Comment by SwickTheGreat** [comment]
didn't realize they were missing, will add them in.

**Comment by SwickTheGreat** [comment]
added in: 277da17e8a27bed7514cd9ed8b69f093af5d0e62
