### ISSUE TITLE
Bug Report: TeaScript seems to be down. 

### ISSUE THREAD

**Issue by DeadSyntaxdev** [EyeDaleHim/Crow-Engine#24]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows 10 64 Bit

## What version of the game are you using? Look in the bottom left corner of the main menu.
Latest Release

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Tried messing with the source code, nothing works might need to find something new.

## Please describe your issue. Provide extensive detail and images if possible.

![image](https://github.com/EyeDaleHim/Crow-Engine/assets/81271362/7310ecce-c5ce-47be-9c2d-488c84fdcd3a)

**Comment by DeadSyntaxdev** [comment]
@EyeDaleHim I recommend removing SScript and TeaScript entirely and finding something else.

**Comment by SwickTheGreat** [comment]
this is new, will check this out but thanks for letting us know. for now just try to remove anything TeaScript/SScript related, if you want to mess around. (it might take a bit and it could break stuff but you do you lol)

**Comment by EyeDaleHim** [comment]
Solved in commit [ba25e36](https://github.com/EyeDaleHim/Crow-Engine/commit/ba25e363e23b7af3ff54f130cbb6c4ff1fd561c3).
