### ISSUE TITLE
Compiling error 

### ISSUE THREAD

**Issue by Enchantedbooz** [EyeDaleHim/Crow-Engine#27]
source/Main.hx:134: characters 19-20 : Unexpected .

**Comment by EyeDaleHim** [comment]
Update to latest Haxe, Crow Engine doesn't like Haxe 4.2.5 anymore.

The latest version is Haxe 4.3.3.

**Comment by Enchantedbooz** [comment]
i got C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flxanimate/3,0,4/flxanimate/animate/FlxAnim.hx:26: characters 9-17 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flxanimate/3,0,4/flxanimate/FlxAnimate.hx:331: characters 97-105 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/FlxSprite.hx:799: characters 18-34 : Unknown identifier : getCamerasLegacy
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/ui/FlxButton.hx:439: characters 18-28 : Unknown identifier : getCameras
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/ui/FlxButton.hx:458: characters 18-28 : Unknown identifier : getCameras
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/FlxSubState.hx:66: characters 19-35 : Unknown identifier : getCamerasLegacy
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/system/FlxBGSprite.hx:23: characters 18-34 : Unknown identifier : getCamerasLegacy
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel-addons/3,2,3/flixel/addons/display/FlxBackdrop.hx:165: characters 19-35 : Unknown identifier : getCamerasLegacy
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel-addons/3,2,3/flixel/addons/display/FlxBackdrop.hx:167: characters 18-25 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel-addons/3,2,3/flixel/addons/display/FlxBackdrop.hx:119: characters 19-35 : Unknown identifier : getCamerasLegacy
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel-addons/3,2,3/flixel/addons/display/FlxBackdrop.hx:121: characters 18-25 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat overrides parent class with different or incomplete type
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/graphics/frames/FlxAtlasFrames.hx:472: characters 18-24 : ... Base field is defined here
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : ... Different number of function arguments
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flxanimate/3,0,4/flxanimate/animate/ButtonEvent.hx:16: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flxanimate/3,0,4/flxanimate/animate/ButtonEvent.hx:23: characters 51-59 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/ui/FlxBar.hx:853: characters 19-35 : Unknown identifier : getCamerasLegacy
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/group/FlxSpriteContainer.hx:91: characters 23-32 : flixel.group.FlxTypedSpriteContainer<flixel.group._FlxSpriteContainer.SpriteContainer.T> has no field container
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/group/FlxContainer.hx:37: characters 14-23 : flixel.group.FlxTypedContainer.T has no field container
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/group/FlxContainer.hx:38: characters 11-20 : flixel.group.FlxTypedContainer.T has no field container
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/group/FlxContainer.hx:40: characters 10-19 : flixel.group.FlxTypedContainer.T has no field container
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/group/FlxContainer.hx:46: characters 10-19 : flixel.group.FlxTypedContainer.T has no field container
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/group/FlxSpriteContainer.hx:89: characters 20-33 : Field get_container is declared 'override' but doesn't override any field
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/group/FlxSpriteContainer.hx:96: characters 54-70 : flixel.group.FlxTypedSpriteContainer<flixel.group._FlxSpriteContainer.SpriteContainer.T> has no field getCamerasLegacy
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/group/FlxSpriteContainer.hx:94: characters 20-36 : Field getCamerasLegacy is declared 'override' but doesn't override any field
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/group/FlxSpriteContainer.hx:101: characters 54-64 : flixel.group.FlxTypedSpriteContainer<flixel.group._FlxSpriteContainer.SpriteContainer.T> has no field getCameras (Suggestions: get_cameras, set_cameras, get_camera)
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/group/FlxSpriteContainer.hx:99: characters 20-30 : Field getCameras is declared 'override' but doesn't override any field (Suggestions: get_cameras, set_cameras, get_camera)
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/input/mouse/FlxMouseEventManager.hx:635: characters 31-41 : flixel.FlxObject has no field getCameras (Suggestions: get_cameras, set_cameras, get_camera)
C:/Users/?/OneDrive/Desktop/engine/EnchantedboozYT/haxelib/flixel/5,8,0/flixel/input/mouse/FlxMouseEventManager.hx:635: characters 18-43 : You can't iterate on a Dynamic value, please specify Iterator or Iterable

**Comment by EyeDaleHim** [comment]
I have a feeling that your libraries are horribly outdated it seems, I do have a feeling it may not be your issue but I'd update just in case

**Comment by Enchantedbooz** [comment]
i can see i if i try to Building the game again

**Comment by Enchantedbooz** [comment]
don't working

**Comment by EyeDaleHim** [comment]
Are there any new or different errors this time around? Keep in mind I am not maintaining this version which is why I'm pinpointing this as just outdated libraries.

**Comment by thegamenig** [comment]
no
